import React from "react";
import type { Metadata } from "next";
// import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ContactProvider } from "@/context/ContactContext";
import { ProductProvider } from "@/context/ProductContext";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
        <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Geist+Mono:wght@400;700&display=swap"
        />
      </head>
      <body className={` antialiased`}>
        <AuthProvider>
          <ProductProvider>
            {" "}
            <ContactProvider>{children}</ContactProvider>
          </ProductProvider>
        </AuthProvider>{" "}
      </body>
    </html>
  );
}
